application: writeraxis-python
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: django
  version: "1.4"

- name: ssl
  version: latest

builtins:
- django_wsgi: on

handlers:
- url: /static/admin
  static_dir: static/admin
  expiration: '0'
- url: /static
  static_dir: static
  expiration: '0'